export const VALUE_PRESEDES_ONE_BEING_COMPARED = -1
export const VALUE_FOLLOWS_ONE_BEING_COMPARED = 1
export const VALUE_EQUIAL_ONE_BEING_COMPARED = 0

export const BASIS_OF_DECIMAL_SYSTEM_OF_CALCULATION = 10

export const FIRST_ARRAY_INDEX = 0

export const ASMX_DEFINITION_STRING = '.asmx'
export const ASPX_DEFINITION_STRING = '.aspx'

export const SUCCESS_RESPONSE_STATUS = 200
